blank_issues_enabled: true
contact_links:
  - name: Bluecoin Core Security Policy
    url: https://github.com/bluecoin/bluecoin/blob/master/SECURITY.md
    about: View security policy
  - name: Bluecoin Core Developers
    url: https://bitcoincore.org
    about: Bluecoin Core homepage
